// // File generated by FlutterFire CLI.
// // ignore_for_file: lines_longer_than_80_chars
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       return web;
//     }
//     // ignore: missing_enum_constant_in_switch
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//     }
//
//     throw UnsupportedError(
//       'DefaultFirebaseOptions are not supported for this platform.',
//     );
//   }
//
//   static const FirebaseOptions web = FirebaseOptions(
//     apiKey: 'AIzaSyCHSdlbIP81g1cy-QVrfJ75bvAf-mIMBCs',
//     appId: '1:834996330799:web:43c608072527d835bcc1da',
//     messagingSenderId: '834996330799',
//     projectId: 'hino-7171e',
//     authDomain: 'hino-7171e.firebaseapp.com',
//     storageBucket: 'hino-7171e.appspot.com',
//     measurementId: 'G-0TMFYXC417',
//   );
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBadZSva_YV7zU6swXSdAaamRP87v-VBgY',
//     appId: '1:834996330799:android:a4b642820f906699bcc1da',
//     messagingSenderId: '834996330799',
//     projectId: 'hino-7171e',
//     storageBucket: 'hino-7171e.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyD9I-Ib2fwkJNs5lqQGimJ-EcgBRZsvpHo',
//     appId: '1:834996330799:ios:eb391bddc9a2d8a2bcc1da',
//     messagingSenderId: '834996330799',
//     projectId: 'hino-7171e',
//     storageBucket: 'hino-7171e.appspot.com',
//     iosClientId: '834996330799-alk5fb84lji5er2o25cfti00gg86tioq.apps.googleusercontent.com',
//     iosBundleId: 'com.thamming.hino',
//   );
// }
